#!/bin/bash
if command -v dialog &> /dev/null
then
    echo dialog is installed > /dev/null
else
    sudo pacman -Syyu
    sudo pacman -S dialog --noconfirm
fi
dialog --inputbox "put in the tarball link from kernel.org:" 8 60 2>kernel.txt
kernel=$(cat kernel.txt)
rm kernel.txt
if [ -z "$kernel" ]; then
	echo "you didnt select a kernel"
    exit
fi
wget ${kernel}
tar xvf linux-*
sudo apt-get install git fakeroot build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison -y
rm *.tar.xz
cd linux*
cp -v /boot/config-$(uname -r) .config
make menuconfig
scripts/config --disable SYSTEM_TRUSTED_KEYS
scripts/config --disable SYSTEM_REVOCATION_KEYS
make
sudo make modules_install
sudo make install