#!/bin/bash
sudo pacman -Syyu --noconfirm
if command -v flatpak &> /dev/null
then
  echo "flatpak is installed" > /dev/null
else
  sudo pacman -Syyu --noconfirm
  sudo pacman -S flatpak --noconfirm
  clear
fi
if lspci | grep -i "vga" | grep -iq "intel"; then
    sudo pacman -S vulkan-intel --noconfirm 
elif lspci | grep -i "vga\|3d" | grep -iq "nvidia"; then
    sudo pacman -S vulkan-nouveau --noconfirm 
elif lspci | grep -i "vga\|display" | grep -iq "amd\|ati"; then
    sudo pacman -S vulkan-radeon --noconfirm 
fi
sudo pacman -S cosmic cosmic-session power-profiles-daemon --noconfirm
flatpak install --user dev.edfloreshz.CosmicTweaks -y
if pgrep -x "lightdm" > /dev/null; then
    sudo systemctl disable lightdm
elif pgrep -x "gdm" > /dev/null; then
    sudo systemctl disable gdm
elif pgrep -x "sddm" > /dev/null; then
    sudo systemctl disable sddm
elif pgrep -x "xdm" > /dev/null; then
    sudo systemctl disable xdm
elif pgrep -x "lxdm" > /dev/null; then
    sudo systemctl disable lxdm
fi
sudo systemctl enable cosmic-greeter
