#!/bin/bash
sudo pacman -Syyu --noconfirm
sudo pacman -S git --noconfirm
yes | sudo pacman -S --needed base-devel
git clone https://aur.archlinux.org/minecraft-launcher.git
cd minecraft-launcher/
makepkg -si --noconfirm
cd ..
rm -rf minecraft-launcher/
