#!/bin/bash
if command -v flatpak &> /dev/null
then
  echo "flatpak is installed" > /dev/null
else
  sudo pacman -Syyu
  sudo pacman -S flatpak --noconfirm
  clear
fi
if flatpak list | grep -q "Sober"; then
    flatpak remove sober -y > /dev/null 2>&1
    flatpak install --user https://sober.vinegarhq.org/sober.flatpakref -y
else
    flatpak install --user https://sober.vinegarhq.org/sober.flatpakref -y
fi
