#!/bin/bash
if command -v flatpak &> /dev/null
then
  echo "flatpak is installed" > /dev/null
else
  sudo pacman -Syyu --noconfirm
  sudo pacman -S flatpak --noconfirm
  clear
fi

if [ -n "$(flatpak list | grep -o sober)" ]; then
    read -p "sober is already installed do you want to reinstall? y/n: " answer
    case $answer in
        [Yy]* ) echo "Proceeding...";;
        [Nn]* ) exit ;;
        * ) echo "Invalid input. Please enter y or n.";;
    esac
    flatpak remove sober -y
    if [ "$(echo $XDG_SESSION_TYPE)" = "wayland" ]; then
      if [ -d "/proc/driver/nvidia" ]; then
        flatpak override --user --socket=x11 --nosocket=wayland
      fi
    fi
    flatpak install --user https://sober.vinegarhq.org/sober.flatpakref -y
else
    if [ "$(echo $XDG_SESSION_TYPE)" = "wayland" ]; then
      if [ -d "/proc/driver/nvidia" ]; then
        flatpak override --user --socket=x11 --nosocket=wayland
      fi
    fi
    flatpak install --user https://sober.vinegarhq.org/sober.flatpakref -y
fi
