#!/bin/bash
sudo pacman -Syyu --noconfirm
if command -v flatpak &> /dev/null
then
    echo flatpak is installed > /dev/null
else
    sudo pacman -S flatpak --noconfirm
fi
cd
git clone https://github.com/MrScratchcat/custom-linux-commands-arch
cd custom-linux-commands-arch
chmod +x * > /dev/null 2>&1
sudo cp * /bin
cd /bin
sudo chmod +x * > /dev/null 2>&1
cd
rm -rf custom-linux-commands-arch
