#!/bin/bash
if command -v docker &> /dev/null; then
    echo "Docker is already installed"
else
    echo "Docker is not installed. Installing..."
    sudo pacman -S docker --noconfirm
fi
sudo docker run -d \
  --name watchtower --restart always \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -e WATCHTOWER_CLEANUP=true \
  -e WATCHTOWER_POLL_INTERVAL=300 \
  containrrr/watchtower
